name: string_to_hex
description: A powerful conversion of String or/and Hash to HEX. It returns a unique HEX, or a unique Color() per provided String/hash.
version: 0.2.1+30
# author: Allan Ramos
homepage: https://github.com/allansrc/string_to_hex

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.17.7
  pedantic: ^1.11.0