name: string_to_hex
description: A powerful conversion of String or/and Hash to HEX. It returns a unique HEX, or a unique Color() per provided String/hash.
version: 0.1.1+1
# author: Allan Ramos
homepage: https://github.com/allansrc/string_to_hex

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0